{{- include "hlib.secret" (dict "context" . "override" "init.secret") -}}
{{- define "init.secret" -}}
stringData:
  USERNAME: {{ .Values.init.username }}
  PASSWORD: {{ .Values.init.password }}
{{- end -}}
